### ISSUE TITLE
Autleveling mitten in der Luft

### ISSUE THREAD

**Issue by sperrmuellklauer** [knutwurst/Marlin-2-0-x-Anycubic-Kossel-Linear-Plus#1]
Moin, ich habe gestern Marlin 2.x.5.6(?) auf den Linear Plus bei uns in der Schule gezogen. Beim durchlaufen des Delta Auto Celibration läuft es leider wie folgt ab:
-Homing (fährt, auch wenn er unten am Druckbett war, wie normal, ganz nach oben zu den Endstops)
-dann fährt er runter und fragt nach der z probe, so weit so gut
-dann fährt er noch wieder n stück runter, leider fängt er dann an die Punkte mitten in der Luft abzutasten, woran liegt das? Außerdem ist nach zwei bis drei Punkten Schluss und er sagt mir "Stow Z Probe"
Ich würde mich über eine schnelle Antwort freuen, da es wir wirklich wichtig ist diesen Drucker zum Laufen zu kriegen. Wäre dann wahrscheinlich auch eine sehr gute Note ;) 
MfG Malte

**Comment by K0SSL** [comment]
Hi, hast du eine Lösung gefunden? Bei mir tritt das selbe Problem auf...

**Comment by sperrmuellklauer** [comment]
Moin, ja schon lange! Es lag einfach daran, dass ich die Endstops nicht richtig verkabelt hatte.. Achtung: die Abbildung auf dem Bild vom ganzen Mainboard ist sehr ungenau, nutze lieber die Abbildung unten rechts welche nur für die Endstops ist und prüfe, ob du es vielleicht auch falsch verkabelt hast. Grüße
