### ISSUE TITLE
UBL Stops

### ISSUE THREAD

**Issue by ghost** [knutwurst/Marlin-2-0-x-Anycubic-Kossel-Linear-Plus#3]
When I try to start the UBL > Step by Step > Build Cold Mesh the Display says 1/25 Points, but always after the 10th he stops and wants me to stow the probe. 
The printer now takes no input and only a hard restart helps

Any Suggestions?

**Comment by knutwurst** [comment]
That's perfectly fine. It's because Marlin assumes that you are going to probe a rectangular bed, but your bed is a circle. So it never reaches the corners. That's why you need to do a "smart fill" after the probing of around 9 to 14 points.

**Comment by LCBozo** [comment]
How does "smart fill" work? I get no response after doing a 10-point mesh and selecting smart fill.
Thanks!
